app:
  message: Message sent to the RabbitMQ queue Successfully
server:
  port: 9090
#Specify rabbitMQ configuration
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ctsshopping?createDatabaseIfNotExist=true&user=root&password=password
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: ctsshopexchange
    queue: ctsqueue
    routingkey: ctsshopkey
